---
abstract: 'logger for qudo.'
author:
  - id:lamanotrama
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.95'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Qudo-Plugin-Logger
no_index:
  directory:
    - inc
    - t
    - xt
requires:
  Log::Dispatch::Configurator::Any: 0
  Qudo: 0
resources:
  license: http://dev.perl.org/licenses/
  repository: git://github.com/nekokak/Qudo-Plugin-Logger.git
version: 0.01
